### ISSUE TITLE
Matplotlib 2.0 Compatibility

### ISSUE THREAD

**Issue by BrianLandry** [taborlab/FlowCal#231]
I tried running flowcal with matplotlib 2.0 and received the following error. Downgrading to 1.5 stopped this from happening. This was done in 1.0.0

~~~~
Beads ID RP20170128b_001...
Loading file "RP20170128b_001.fcs"...
Performing data transformation...
Performing gating...
Plotting density plot and histogram...
Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build\bdist.win32\egg\FlowCal\excel_ui.py", line 1435, in <module>
  File "build\bdist.win32\egg\FlowCal\excel_ui.py", line 1350, in run
  File "build\bdist.win32\egg\FlowCal\excel_ui.py", line 431, in process_beads_table
  File "build\bdist.win32\egg\FlowCal\plot.py", line 1507, in density_and_hist
  File "build\bdist.win32\egg\FlowCal\plot.py", line 1012, in density2d
  File "C:\Anaconda2\lib\site-packages\matplotlib\axes\_base.py", line 2948, in set_xscale
    ax.xaxis._set_scale(value, **kwargs)
  File "C:\Anaconda2\lib\site-packages\matplotlib\axis.py", line 710, in _set_scale
    self._scale.set_default_locators_and_formatters(self)
  File "build\bdist.win32\egg\FlowCal\plot.py", line 545, in set_default_locators_and_formatters
  File "C:\Anaconda2\lib\site-packages\matplotlib\ticker.py", line 2067, in __init__
    self._linthresh = transform.linthresh
AttributeError: '_LogicleTransform' object has no attribute 'linthresh'
Press [Enter] to finish...
~~~~

**Comment by castillohair** [comment]
I'm gonna close this in favor in #233, since it has more detail (like library versions) and is using the most recent version.

Also, version 1.0.0 (which you are claiming you used) would not have produced this error, since it doesn't have logicle scaling.
