### ISSUE TITLE
during installation using anaconda version 

### ISSUE THREAD

**Issue by shuvadeep** [taborlab/FlowCal#357]
I am facing this error while installing 
"/Users/shuvadeepmaity/Downloads/FlowCal-master/Install\ FlowCal\ \(macOS\) ; exit;
(base) shuvadeepmaity@Shuvadeeps-MacBook-Air ~ % /Users/shuvadeepmaity/Downloads/FlowCal-master/Install\ FlowCal\ \(macOS\) ; exit;
Traceback (most recent call last):
  File "/Users/shuvadeepmaity/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/shuvadeepmaity/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/shuvadeepmaity/opt/anaconda3/lib/python3.9/site-packages/pip/__main__.py", line 9, in <module>
    if sys.path[0] in ("", os.getcwd()):
PermissionError: [Errno 1] Operation not permitted
python: can't open file 'setup.py': [Errno 1] Operation not permitted
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed."

I am using python version Python 3.9.12

**Comment by castillohair** [comment]
Hi @shuvadeep. What macOS version are you using?
